import type { Section } from '../../../types';

export const compilationPipelineSections: Section[] = [
  {
    id: 'v8-compilation-pipeline',
    title: 'The Compilation Pipeline',
    content: [
      {
        type: 'text',
        content:
          "V8 uses a multi-tier compilation strategy to balance startup speed with peak performance. When JavaScript source code enters V8, it passes through several stages — each one trading compilation time for faster execution. This approach lets V8 start running code almost instantly (via an interpreter) while selectively optimizing hot functions in the background.",
      },
      {
        type: 'heading',
        level: 2,
        text: 'From Source Code to Bytecode',
      },
      {
        type: 'text',
        content:
          "The first step is **parsing**. V8's parser (and pre-parser for lazy parsing) converts JavaScript source text into an Abstract Syntax Tree (AST). The AST is a tree representation of the syntactic structure of the code. V8 uses lazy parsing for functions that aren't immediately invoked — it only fully parses a function when it's first called, which significantly reduces startup time for large codebases. The scanner (lexer) breaks the source into tokens, and the parser assembles them into AST nodes according to the ECMAScript grammar.",
      },
      {
        type: 'diagram',
        diagramId: 'v8-pipeline',
        caption:
          'The V8 compilation pipeline: Source -> Parser -> AST -> Ignition -> Bytecode -> Sparkplug/Maglev/TurboFan -> Machine Code',
      },
      {
        type: 'key-concept',
        title: 'Lazy Parsing',
        content:
          "V8 doesn't parse every function eagerly. Inner functions are pre-parsed (syntax-checked but not fully compiled) until they are first called. This is critical for web performance — a page may load megabytes of JavaScript but only execute a fraction of it on startup. Pre-parsing validates syntax and identifies variable references without generating bytecode.",
      },
      {
        type: 'heading',
        level: 2,
        text: 'Ignition: The Bytecode Interpreter',
      },
      {
        type: 'text',
        content:
          "Once the AST is built, V8's **Ignition** interpreter compiles it into a compact bytecode format and executes it. Ignition is a register-based interpreter with an accumulator register. Each bytecode instruction is a single byte opcode followed by operands. Ignition was introduced to reduce memory overhead (bytecode is much more compact than machine code) and to provide a consistent baseline for collecting type feedback that the optimizing compilers use.",
      },
      {
        type: 'code',
        language: 'javascript',
        code: `// JavaScript source
function add(a, b) {
  return a + b;
}`,
        caption: 'A simple function before compilation',
      },
      {
        type: 'code',
        language: 'text',
        code: `// Ignition bytecode (simplified)
// Run: node --print-bytecode --print-bytecode-filter=add script.js

[generated bytecode for function: add]
Parameter count 3
Register count 0
  0x...  @  0 : 25 02          Ldar a1        // Load argument 'a' into accumulator
  0x...  @  2 : 34 03 00       Add a2, [0]    // Add argument 'b' to accumulator
  0x...  @  5 : a9             Return          // Return accumulator value`,
        caption:
          'The bytecode Ignition generates — compact register-based instructions',
      },
      {
        type: 'heading',
        level: 2,
        text: 'Sparkplug: The Baseline Compiler',
      },
      {
        type: 'text',
        content:
          "**Sparkplug** is V8's non-optimizing baseline compiler, introduced in V8 v9.1. It compiles Ignition bytecodes directly to machine code without any intermediate representation (IR). Sparkplug doesn't perform any optimization — it simply translates each bytecode to its machine-code equivalent as fast as possible. This gives a 5-15% speedup over interpreted bytecode at minimal compilation cost. Sparkplug code shares the same stack frame layout as Ignition, so switching between the two is seamless.",
      },
      {
        type: 'info',
        variant: 'tip',
        title: 'Why Sparkplug Matters',
        content:
          "Sparkplug fills the gap between interpreted bytecode and optimized machine code. Before Sparkplug, code had to wait for TurboFan optimization or run in the interpreter. Sparkplug's compilation is so fast (it's essentially a single pass over bytecodes with no register allocation) that it can run during the first execution of a function, providing an immediate performance uplift.",
      },
      {
        type: 'heading',
        level: 2,
        text: 'Maglev: The Mid-Tier Optimizing Compiler',
      },
      {
        type: 'text',
        content:
          "**Maglev** is V8's mid-tier optimizing compiler, introduced in V8 v11.3 (Chrome 114). It sits between Sparkplug and TurboFan in the compilation tier hierarchy. Maglev uses type feedback collected by Ignition to generate optimized machine code, but it compiles much faster than TurboFan because it uses a simpler SSA-based IR and performs fewer optimization passes. Maglev targets \"warm\" functions — those called enough times to benefit from optimization but that may not justify the full cost of TurboFan compilation.",
      },
      {
        type: 'key-concept',
        title: 'Tier-Up & Tier-Down',
        content:
          "V8 promotes (\"tiers up\") code to higher optimization levels based on execution counters and type feedback. A function starts in Ignition, may be compiled by Sparkplug on first execution, then Maglev after it becomes warm, and finally TurboFan for hot loops and critical functions. If optimized code encounters a type assumption violation, V8 **deoptimizes** (\"tiers down\") — discarding the optimized code and falling back to Ignition/Sparkplug bytecode. Deoptimization is expensive and should be avoided in performance-critical code.",
      },
      {
        type: 'heading',
        level: 2,
        text: 'TurboFan: The Optimizing Compiler',
      },
      {
        type: 'text',
        content:
          "**TurboFan** is V8's top-tier optimizing compiler. It builds a graph-based intermediate representation (a \"sea of nodes\" IR) from bytecodes and type feedback, then applies aggressive optimizations: inlining, escape analysis, load/store elimination, constant folding, dead code elimination, range analysis, loop peeling, and more. TurboFan performs instruction selection, register allocation (using a linear-scan allocator), and code generation for the target architecture (x64, ARM64, etc.). The result is highly optimized machine code that can rival ahead-of-time compiled languages for hot code paths.",
      },
      {
        type: 'comparison',
        leftTitle: 'Interpreter (Ignition)',
        rightTitle: 'Optimized (TurboFan)',
        leftContent:
          'Fast to start, slow to execute. Each bytecode is dispatched through a handler. No type specialization. Good for code that runs once or rarely. Low memory overhead.',
        rightContent:
          'Slow to compile, fast to execute. Machine code with inlined type checks. Speculative optimizations based on type feedback. Ideal for hot loops and frequently called functions. Higher memory overhead.',
      },
      {
        type: 'info',
        variant: 'warning',
        title: 'Deoptimization Bailouts',
        content:
          'When TurboFan-optimized code encounters a value whose type doesn\'t match the feedback it was compiled with (e.g., a function that always received integers suddenly receives a string), V8 must deoptimize. This discards the machine code, reconstructs the interpreter frame, and resumes in Ignition. Repeated deoptimizations cause a function to be marked as "don\'t optimize," permanently leaving it in lower tiers. Write type-stable code to avoid this.',
      },
    ],
  },
];
